---
# defaults file for filetree_create

# Controller object lists
controller_credentials: []
controller_execution_environments: []
controller_hosts: []
controller_inventories: []
controller_inventory_sources: []
controller_job_templates: []
aap_organizations: []
controller_projects: []
controller_roles: []
controller_schedules: []
controller_settings: []
aap_teams: []
aap_user_accounts: []
controller_workflows: []

# Output directory path
output_path: "/tmp/filetree_output"

# Gateway - Non-Flat Folder Names
filetree_create_aap_applications: "aap_applications.d"

# Controller - Non-Flat Folder Names
filetree_create_controller_applications: "controller_applications.d"
filetree_create_controller_labels: "controller_labels.d"
filetree_create_controller_credentials: "controller_credentials.d"
filetree_create_controller_credential_input_sources: "controller_credential_input_sources.d"
filetree_create_controller_notifications: "controller_notification_templates.d"
filetree_create_controller_projects: "controller_projects.d"
filetree_create_controller_inventories: "controller_inventories.d"
filetree_create_controller_inventory_sources: "controller_inventory_sources.d"
filetree_create_controller_hosts: "controller_hosts.d"
filetree_create_controller_groups: "controller_groups.d"
filetree_create_controller_templates: "controller_job_templates.d"
filetree_create_controller_workflow_job_templates: "controller_workflow_job_templates.d"
filetree_create_controller_schedules: "controller_schedules.d"
filetree_create_controller_user_accounts: "controller_users.d"
filetree_create_controller_teams: "controller_teams.d"
filetree_create_controller_user_roles: "controller_roles.d/user_roles.d"
filetree_create_controller_team_roles: "controller_roles.d/team_roles.d"

# EDA - Non-Flat Folder Names
filetree_create_eda_projects: "eda_projects.d"
filetree_create_eda_rulebook_activations: "eda_rulebook_activations.d"

# Maximum number of objects to return from the list. If a list view returns more an max_objects an exception will be raised
query_controller_api_max_objects: 10000
query_gateway_api_max_objects: 10000
query_eda_api_max_objects: 10000
query_hub_api_max_objects: 10000
export_related_objects: false
skip_inventory_sources: false
skip_inventory_hosts: false
skip_inventory_groups: false
controller_configuration_filetree_create_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"
eda_configuration_filetree_create_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"
hub_configuration_filetree_create_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"

input_tag:
  - all
organization: 'ORGANIZATIONLESS'

secrets_as_variables: true
secrets_as_variables_prefix: "vaulted"
...
