---
# defaults file for filetree_create

# Controller object lists
controller_credentials: []
controller_execution_environments: []
controller_hosts: []
controller_inventories: []
controller_inventory_sources: []
controller_job_templates: []
aap_organizations: []
controller_projects: []
controller_roles: []
controller_schedules: []
controller_settings: []
aap_teams: []
aap_user_accounts: []
controller_workflows: []

# Output directory path
output_path: "/tmp/filetree_output"

# Gateway - Non-Flat Folder Names
filetree_create_aap_applications: "aap_applications.d"

# Controller - Non-Flat Folder Names
filetree_create_controller_applications: "controller_applications.d"
filetree_create_controller_labels: "controller_labels.d"
filetree_create_controller_credentials: "controller_credentials.d"
filetree_create_controller_credential_input_sources: "controller_credential_input_sources.d"
filetree_create_controller_notifications: "controller_notification_templates.d"
filetree_create_controller_projects: "controller_projects.d"
filetree_create_controller_inventories: "controller_inventories.d"
filetree_create_controller_inventory_sources: "controller_inventory_sources.d"
filetree_create_controller_hosts: "controller_hosts.d"
filetree_create_controller_groups: "controller_groups.d"
filetree_create_controller_templates: "controller_job_templates.d"
filetree_create_controller_workflow_job_templates: "controller_workflow_job_templates.d"
filetree_create_controller_schedules: "controller_schedules.d"
filetree_create_controller_user_accounts: "controller_users.d"
filetree_create_controller_teams: "controller_teams.d"
filetree_create_controller_user_roles: "controller_roles.d/user_roles.d"
filetree_create_controller_team_roles: "controller_roles.d/team_roles.d"

# EDA - Non-Flat Folder Names
filetree_create_eda_projects: "eda_projects.d"
filetree_create_eda_rulebook_activations: "eda_rulebook_activations.d"

# Maximum number of objects to return from the list. If a list view returns more an max_objects an exception will be raised
query_controller_api_max_objects: 10000
query_gateway_api_max_objects: 10000
query_eda_api_max_objects: 10000
query_hub_api_max_objects: 10000
export_related_objects: false
skip_inventory_sources: false
skip_inventory_hosts: false
skip_inventory_groups: false
controller_configuration_filetree_create_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"
eda_configuration_filetree_create_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"
hub_configuration_filetree_create_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"

secrets_as_variables: true
secrets_as_variables_prefix: "vaulted"

organization: 'ORGANIZATIONLESS'

input_tag:
  - all
valid_tags:
  - all
  - controller
  - controller_settings
  - controller_credentials
  - controller_credential_types
  - controller_execution_environments
  - controller_groups
  - controller_hosts
  - controller_inventories
  - controller_inventory_sources
  - controller_job_templates
  - controller_notification_templates
  - controller_organizations
  - controller_projects
  - controller_roles
  - controller_teams
  - controller_users
  - controller_workflow_job_templates
  - controller_instance_groups
  - controller_applications
  - controller_labels
  - controller_schedules
  - controller_gateway_authenticator
  - controller_gateway_authenticator_maps
  - gateway
  - gateway_applications
  - gateway_authenticator_maps
  - gateway_authenticators
  - gateway_http_ports
  - gateway_organizations
  - gateway_role_definitions
  - gateway_role_user_assignments
  - gateway_routes
  - gateway_service_clusters
  - gateway_service_keys
  - gateway_service_nodes
  - gateway_services
  - gateway_settings
  - gateway_teams
  - gateway_users
  - eda
  - eda_credential_types
  - eda_credentials
  - eda_decision_environments
  - eda_event_streams
  - eda_projects
  - eda_rulebook_activations
  - hub
  - hub_namespaces
  - hub_collections
  - hub_collection_remotes
  - hub_collection_repositories
  - hub_ee_registries
  - hub_ee_repositories
...
