---
namespace: infra
name: aap_configuration_extended
version: 1.0.0-devel
description: A collection of roles to extend functionality of aap_configuration collection
readme: README.md
authors:
    - Andrew Huffman
    - Adebisi Oyawale @aoyawale
    - Kedar Kulkarni @kedark3
    - Tom Page @Tompage1994
    - Sean Sullivan @sean-m-sullivan
    - David Danielsson @djdanielsson
repository: https://github.com/redhat-cop/aap_configuration_extended/
issues: https://github.com/redhat-cop/aap_configuration_extended/issues
build_ignore:
    - galaxy.yml.j2
    - release.yml
    - .github
    - '*.tar.gz'
license:
    - GPL-3.0-or-later
tags:
    - controller
    - collection
    - aap_configuration_extended
    - automation_platform
    - infrastructure
...
