"""Schemas for Automation Controller resource types."""

from __future__ import annotations

from aap_config_validate.models import Field, ResourceSchema

CONTROLLER_SCHEMAS = [
    ResourceSchema(
        var="controller_settings",
        roles=["controller_settings"],
        aliases=["controller_settings"],
        component="controller",
        is_list=True,
        item_schema={
            "settings": Field(type="dict"),
            "name": Field(type="str"),
            "value": Field(type="any"),
        },
    ),
    ResourceSchema(
        var="controller_instances",
        roles=["controller_instances"],
        component="controller",
        item_id_field="hostname",
        item_schema={
            "hostname": Field(type="str", required=True),
            "capacity_adjustment": Field(type="float"),
            "enabled": Field(type="bool"),
            "managed_by_policy": Field(type="bool"),
            "node_type": Field(type="str"),
            "node_state": Field(type="str"),
            "listener_port": Field(type="int"),
            "peers": Field(type="list"),
            "peers_from_control_nodes": Field(type="bool"),
            "state": Field(
                type="str",
                choices=["present", "absent", "exists", "enabled", "disabled"],
            ),
        },
    ),
    ResourceSchema(
        var="controller_labels",
        roles=["controller_labels"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "organization": Field(type="str", required=True, xref="aap_organizations.name"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="controller_credential_types",
        roles=["controller_credential_types"],
        aliases=["credential_types"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "injectors": Field(type="dict"),
            "inputs": Field(type="dict"),
            "kind": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="controller_credentials",
        roles=["controller_credentials"],
        aliases=["credentials"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "copy_from": Field(type="str"),
            "description": Field(type="str"),
            "organization": Field(type="str|dict", xref="aap_organizations.name"),
            "credential_type": Field(type="str|dict", required=True),
            "inputs": Field(type="dict"),
            "user": Field(type="str|dict"),
            "team": Field(type="str|dict"),
            "update_secrets": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "roles": Field(type="list"),
        },
    ),
    ResourceSchema(
        var="controller_credential_input_sources",
        roles=["controller_credential_input_sources"],
        component="controller",
        item_id_field="target_credential",
        item_schema={
            "target_credential": Field(type="str", required=True),
            "input_field_name": Field(type="str", required=True),
            "source_credential": Field(type="str"),
            "description": Field(type="str"),
            "metadata": Field(type="dict"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="controller_instance_groups",
        roles=["controller_instance_groups"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "credential": Field(type="str"),
            "is_container_group": Field(type="bool"),
            "policy_instance_percentage": Field(type="int"),
            "policy_instance_minimum": Field(type="int"),
            "policy_instance_list": Field(type="list"),
            "max_concurrent_jobs": Field(type="int"),
            "max_forks": Field(type="int"),
            "pod_spec_override": Field(type="str"),
            "instances": Field(type="list"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "roles": Field(type="list"),
        },
    ),
    ResourceSchema(
        var="controller_execution_environments",
        roles=["controller_execution_environments"],
        aliases=["execution_environments"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "image": Field(type="str", required=True),
            "organization": Field(type="str|dict", xref="aap_organizations.name"),
            "credential": Field(type="str"),
            "pull": Field(type="str", choices=["always", "missing", "never"]),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="controller_notifications",
        roles=["controller_notification_templates"],
        aliases=["notification_templates", "controller_notification_templates"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "copy_from": Field(type="str"),
            "description": Field(type="str"),
            "organization": Field(type="str|dict", xref="aap_organizations.name"),
            "notification_type": Field(type="str"),
            "notification_configuration": Field(type="dict"),
            "messages": Field(type="dict"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="controller_projects",
        roles=["controller_projects"],
        aliases=["projects"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "copy_from": Field(type="str"),
            "description": Field(type="str"),
            "scm_type": Field(type="str", choices=["git", "svn", "insights", "archive", ""]),
            "scm_url": Field(type="str"),
            "default_environment": Field(type="str|dict"),
            "local_path": Field(type="str"),
            "scm_branch": Field(type="str"),
            "scm_refspec": Field(type="str"),
            "credential": Field(type="str|dict", aliases=["scm_credential"]),
            "signature_validation_credential": Field(type="str|dict"),
            "scm_clean": Field(type="bool"),
            "scm_delete_on_update": Field(type="bool"),
            "scm_track_submodules": Field(type="bool"),
            "scm_update_on_launch": Field(type="bool"),
            "scm_update_cache_timeout": Field(type="int"),
            "allow_override": Field(type="bool"),
            "timeout": Field(type="int", aliases=["job_timeout"]),
            "job_timeout": Field(type="int", aliases=["timeout"]),
            "custom_virtualenv": Field(type="str"),
            "organization": Field(type="str|dict", xref="aap_organizations.name"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "wait": Field(type="bool"),
            "update_project": Field(type="bool"),
            "interval": Field(type="int"),
            "notification_templates_started": Field(type="list"),
            "notification_templates_success": Field(type="list"),
            "notification_templates_error": Field(type="list"),
            "roles": Field(type="list"),
        },
    ),
    ResourceSchema(
        var="controller_inventories",
        roles=["controller_inventories"],
        aliases=["inventory"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "copy_from": Field(type="str"),
            "description": Field(type="str"),
            "organization": Field(type="str|dict", required=True, xref="aap_organizations.name"),
            "instance_groups": Field(type="list"),
            "input_inventories": Field(type="list"),
            "variables": Field(type="str|dict"),
            "kind": Field(type="str"),
            "host_filter": Field(type="str"),
            "prevent_instance_group_fallback": Field(type="bool"),
            "source_vars": Field(type="str|dict"),
            "update_cache_timeout": Field(type="int"),
            "limit": Field(type="str"),
            "verbosity": Field(type="int"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "roles": Field(type="list"),
        },
    ),
    ResourceSchema(
        var="controller_inventory_sources",
        roles=["controller_inventory_sources", "controller_inventory_source_update"],
        aliases=["inventory_sources"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "inventory": Field(type="str|dict", required=True, xref="controller_inventories.name"),
            "organization": Field(type="str|dict", xref="aap_organizations.name"),
            "source": Field(type="str"),
            "source_path": Field(type="str"),
            "source_vars": Field(type="str|dict"),
            "enabled_var": Field(type="str"),
            "enabled_value": Field(type="str"),
            "host_filter": Field(type="str"),
            "limit": Field(type="str"),
            "credential": Field(type="str|dict"),
            "execution_environment": Field(type="str|dict"),
            "overwrite": Field(type="bool"),
            "overwrite_vars": Field(type="bool"),
            "custom_virtualenv": Field(type="str"),
            "timeout": Field(type="int"),
            "verbosity": Field(type="int", choices=[0, 1, 2, 3, 4, 5]),
            "update_on_launch": Field(type="bool"),
            "update_cache_timeout": Field(type="int"),
            "source_project": Field(type="str|dict", xref="controller_projects.name"),
            "scm_branch": Field(type="str"),
            "wait": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "notification_templates_started": Field(type="list"),
            "notification_templates_success": Field(type="list"),
            "notification_templates_error": Field(type="list"),
        },
    ),
    ResourceSchema(
        var="controller_hosts",
        roles=["controller_hosts"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "inventory": Field(type="str", required=True, xref="controller_inventories.name"),
            "enabled": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "variables": Field(type="str|dict"),
        },
    ),
    ResourceSchema(
        var="controller_bulk_hosts",
        roles=["controller_bulk_host_create"],
        component="controller",
        item_id_field="inventory",
        item_schema={
            "hosts": Field(type="list", required=True),
            "inventory": Field(type="str", required=True, xref="controller_inventories.name"),
        },
    ),
    ResourceSchema(
        var="controller_groups",
        roles=["controller_host_groups"],
        aliases=["controller_host_groups"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "inventory": Field(type="str", required=True, xref="controller_inventories.name"),
            "variables": Field(type="str|dict"),
            "hosts": Field(type="list"),
            "children": Field(type="list"),
            "preserve_existing_hosts": Field(type="bool"),
            "preserve_existing_children": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="controller_templates",
        roles=["controller_job_templates"],
        aliases=["job_templates"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "copy_from": Field(type="str"),
            "description": Field(type="str"),
            "execution_environment": Field(type="str|dict"),
            "custom_virtualenv": Field(type="str"),
            "job_type": Field(type="str", choices=["run", "check"]),
            "inventory": Field(type="str|dict", xref="controller_inventories.name"),
            "organization": Field(type="str|dict", xref="aap_organizations.name"),
            "project": Field(type="str|dict", xref="controller_projects.name"),
            "playbook": Field(type="str"),
            "credentials": Field(type="str|list", xref="controller_credentials.name"),
            "forks": Field(type="int"),
            "limit": Field(type="str"),
            "verbosity": Field(type="int", choices=[0, 1, 2, 3, 4, 5]),
            "extra_vars": Field(type="str|dict"),
            "job_tags": Field(type="str"),
            "force_handlers": Field(type="bool"),
            "skip_tags": Field(type="str"),
            "start_at_task": Field(type="str"),
            "diff_mode": Field(type="bool"),
            "use_fact_cache": Field(type="bool", aliases=["fact_caching_enabled"]),
            "fact_caching_enabled": Field(type="bool", aliases=["use_fact_cache"]),
            "host_config_key": Field(type="str"),
            "ask_scm_branch_on_launch": Field(type="bool"),
            "ask_diff_mode_on_launch": Field(type="bool"),
            "ask_variables_on_launch": Field(type="bool"),
            "ask_extra_vars": Field(type="bool", aliases=["ask_variables_on_launch"]),
            "ask_limit_on_launch": Field(type="bool"),
            "ask_tags_on_launch": Field(type="bool", aliases=["ask_tags"]),
            "ask_tags": Field(type="bool", aliases=["ask_tags_on_launch"]),
            "ask_skip_tags_on_launch": Field(type="bool", aliases=["ask_skip_tags"]),
            "ask_skip_tags": Field(type="bool", aliases=["ask_skip_tags_on_launch"]),
            "ask_job_type_on_launch": Field(type="bool"),
            "ask_verbosity_on_launch": Field(type="bool"),
            "ask_inventory_on_launch": Field(type="bool"),
            "ask_credential_on_launch": Field(type="bool"),
            "ask_execution_environment_on_launch": Field(type="bool"),
            "ask_forks_on_launch": Field(type="bool"),
            "ask_instance_groups_on_launch": Field(type="bool"),
            "ask_job_slice_count_on_launch": Field(type="bool"),
            "ask_labels_on_launch": Field(type="bool"),
            "ask_timeout_on_launch": Field(type="bool"),
            "prevent_instance_group_fallback": Field(type="bool"),
            "concurrent_jobs_enabled": Field(type="bool"),
            "survey_enabled": Field(type="bool"),
            "survey_spec": Field(type="dict", aliases=["survey"]),
            "survey": Field(type="dict", aliases=["survey_spec"]),
            "become_enabled": Field(type="bool"),
            "allow_simultaneous": Field(type="bool"),
            "timeout": Field(type="int"),
            "instance_groups": Field(type="list"),
            "job_slice_count": Field(type="int"),
            "webhook_service": Field(type="str"),
            "webhook_credential": Field(type="str"),
            "scm_branch": Field(type="str"),
            "labels": Field(type="list"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "notification_templates_started": Field(type="list"),
            "notification_templates_success": Field(type="list"),
            "notification_templates_error": Field(type="list"),
            "roles": Field(type="list"),
        },
    ),
    ResourceSchema(
        var="controller_workflows",
        roles=["controller_workflow_job_templates"],
        aliases=["workflow_job_templates"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "copy_from": Field(type="str"),
            "description": Field(type="str"),
            "extra_vars": Field(type="str|dict"),
            "allow_simultaneous": Field(type="bool"),
            "organization": Field(type="str|dict", xref="aap_organizations.name"),
            "ask_variables_on_launch": Field(type="bool"),
            "inventory": Field(type="str|dict", xref="controller_inventories.name"),
            "limit": Field(type="str"),
            "labels": Field(type="list"),
            "scm_branch": Field(type="str"),
            "ask_inventory_on_launch": Field(type="bool"),
            "ask_scm_branch_on_launch": Field(type="bool"),
            "ask_limit_on_launch": Field(type="bool"),
            "webhook_service": Field(type="str"),
            "webhook_credential": Field(type="str|dict"),
            "survey_enabled": Field(type="bool"),
            "survey_spec": Field(type="dict", aliases=["survey"]),
            "survey": Field(type="dict", aliases=["survey_spec"]),
            "job_tags": Field(type="str|list"),
            "skip_tags": Field(type="str|list"),
            "ask_tags_on_launch": Field(type="bool", aliases=["ask_tags"]),
            "ask_tags": Field(type="bool", aliases=["ask_tags_on_launch"]),
            "ask_labels_on_launch": Field(type="bool"),
            "ask_skip_tags_on_launch": Field(type="bool", aliases=["ask_skip_tags"]),
            "ask_skip_tags": Field(type="bool", aliases=["ask_skip_tags_on_launch"]),
            "workflow_nodes": Field(type="list"),
            "destroy_current_nodes": Field(type="bool", aliases=["destroy_current_schema"]),
            "destroy_current_schema": Field(type="bool", aliases=["destroy_current_nodes"]),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
            "notification_templates_started": Field(type="list"),
            "notification_templates_success": Field(type="list"),
            "notification_templates_error": Field(type="list"),
            "notification_templates_approvals": Field(type="list"),
            "roles": Field(type="list"),
            "simplified_workflow_nodes": Field(type="list"),
            "schedules": Field(type="list"),
        },
    ),
    ResourceSchema(
        var="controller_schedules",
        roles=["controller_schedules"],
        aliases=["schedules"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "rrule": Field(type="str"),
            "extra_data": Field(type="dict"),
            "inventory": Field(type="str"),
            "credentials": Field(type="list"),
            "scm_branch": Field(type="str"),
            "execution_environment": Field(type="str|dict"),
            "forks": Field(type="int"),
            "instance_groups": Field(type="list"),
            "job_slice_count": Field(type="int"),
            "labels": Field(type="list"),
            "timeout": Field(type="int"),
            "job_type": Field(type="str"),
            "job_tags": Field(type="str"),
            "skip_tags": Field(type="str"),
            "limit": Field(type="str"),
            "diff_mode": Field(type="bool"),
            "verbosity": Field(type="int", choices=[0, 1, 2, 3, 4, 5]),
            "organization": Field(type="str"),
            "unified_job_template": Field(type="str"),
            "dtstart": Field(type="str"),
            "dtend": Field(type="str"),
            "timezone": Field(type="str"),
            "enabled": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="controller_roles",
        roles=["controller_roles"],
        component="controller",
        item_id_field="role",
        item_schema={
            "role": Field(type="str"),
            "roles": Field(type="list"),
            "user": Field(type="str"),
            "users": Field(type="list"),
            "team": Field(type="str"),
            "teams": Field(type="list"),
            "target_team": Field(type="str"),
            "target_teams": Field(type="list"),
            "inventory": Field(type="str"),
            "inventories": Field(type="list"),
            "job_template": Field(type="str"),
            "job_templates": Field(type="list"),
            "workflow": Field(type="str"),
            "workflows": Field(type="list"),
            "credential": Field(type="str"),
            "credentials": Field(type="list"),
            "organization": Field(type="str"),
            "organizations": Field(type="list"),
            "lookup_organization": Field(type="str"),
            "project": Field(type="str"),
            "projects": Field(type="list"),
            "instance_groups": Field(type="list"),
            "state": Field(type="str", choices=["present", "absent"]),
        },
    ),
    ResourceSchema(
        var="controller_launch_jobs",
        roles=["controller_job_launch"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "job_type": Field(type="str"),
            "inventory": Field(type="str"),
            "organization": Field(type="str|dict"),
            "credentials": Field(type="list"),
            "extra_vars": Field(type="str|dict"),
            "limit": Field(type="str"),
            "tags": Field(type="str"),
            "scm_branch": Field(type="str"),
            "skip_tags": Field(type="str"),
            "verbosity": Field(type="int"),
            "diff_mode": Field(type="bool"),
            "credential_passwords": Field(type="dict"),
            "execution_environment": Field(type="str|dict"),
            "forks": Field(type="int"),
            "instance_groups": Field(type="list"),
            "job_slice_count": Field(type="int"),
            "labels": Field(type="list"),
            "job_timeout": Field(type="int"),
            "wait": Field(type="bool"),
            "interval": Field(type="int"),
            "timeout": Field(type="int"),
        },
    ),
    ResourceSchema(
        var="controller_workflow_launch_jobs",
        roles=["controller_workflow_launch"],
        component="controller",
        item_schema={
            "name": Field(type="str", required=True),
            "organization": Field(type="str"),
            "inventory": Field(type="str"),
            "limit": Field(type="str"),
            "scm_branch": Field(type="str"),
            "extra_vars": Field(type="str|dict"),
            "wait": Field(type="bool"),
            "interval": Field(type="int"),
            "timeout": Field(type="int"),
        },
    ),
]
