"""Schemas for Event-Driven Ansible resource types."""

from __future__ import annotations

from aap_config_validate.models import Field, ResourceSchema

EDA_SCHEMAS = [
    ResourceSchema(
        var="eda_credential_types",
        roles=["eda_credential_types"],
        component="eda",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "inputs": Field(type="dict"),
            "injectors": Field(type="dict"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="eda_credentials",
        roles=["eda_credentials"],
        component="eda",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "organization": Field(type="str", aliases=["organization_name"]),
            "credential_type": Field(type="str", required=True, aliases=["credential_type_name"]),
            "inputs": Field(type="dict"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="eda_credential_input_sources",
        roles=["eda_credential_input_sources"],
        component="eda",
        item_id_field="target_credential",
        item_schema={
            "target_credential": Field(type="str", required=True),
            "input_field_name": Field(type="str", required=True),
            "source_credential": Field(type="str"),
            "description": Field(type="str"),
            "organization": Field(type="str", required=True, aliases=["organization_name"]),
            "metadata": Field(type="dict"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="eda_controller_tokens",
        roles=["eda_controller_tokens"],
        component="eda",
        item_schema={
            "name": Field(type="str", required=True),
            "description": Field(type="str"),
            "token": Field(type="str"),
        },
    ),
    ResourceSchema(
        var="eda_projects",
        roles=["eda_projects"],
        component="eda",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "url": Field(type="str", aliases=["scm_url"]),
            "scm_url": Field(type="str", aliases=["url"]),
            "scm_branch": Field(type="str"),
            "credential": Field(type="str"),
            "organization": Field(type="str", aliases=["organization_name"]),
            "proxy": Field(type="str"),
            "sync": Field(type="bool"),
            "wait": Field(type="bool"),
            "timeout": Field(type="int"),
            "tls_validation": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="eda_event_streams",
        roles=["eda_event_streams"],
        component="eda",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "credential_name": Field(type="str"),
            "organization": Field(type="str"),
            "headers": Field(type="str"),
            "forward_events": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="eda_decision_environments",
        roles=["eda_decision_environments"],
        component="eda",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "image_url": Field(type="str"),
            "credential": Field(type="str"),
            "organization": Field(type="str", aliases=["organization_name"]),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="eda_rulebook_activations",
        roles=["eda_rulebook_activations"],
        component="eda",
        item_schema={
            "name": Field(type="str", required=True),
            "description": Field(type="str"),
            "project": Field(type="str", xref="eda_projects.name"),
            "rulebook": Field(type="str"),
            "decision_environment": Field(type="str", xref="eda_decision_environments.name"),
            "awx_token": Field(type="str"),
            "restart_policy": Field(type="str", choices=["always", "never", "on-failure"]),
            "extra_vars": Field(type="str|dict"),
            "enabled": Field(type="bool"),
            "organization": Field(type="str"),
            "eda_credentials": Field(type="list"),
            "k8s_service_name": Field(type="str"),
            "swap_single_source": Field(type="bool"),
            "event_streams": Field(type="list"),
            "log_level": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
]
