"""Schemas for Gateway resource types."""

from __future__ import annotations

from aap_config_validate.models import Field, ResourceSchema

GATEWAY_SCHEMAS = [
    ResourceSchema(
        var="gateway_authenticators",
        roles=["gateway_authenticators"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "slug": Field(type="str"),
            "enabled": Field(type="bool"),
            "create_objects": Field(type="bool"),
            "remove_users": Field(type="bool"),
            "configuration": Field(type="dict"),
            "auto_migrate_users_to": Field(type="str"),
            "type": Field(type="str"),
            "order": Field(type="int"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_authenticator_maps",
        roles=["gateway_authenticator_maps"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "authenticator": Field(type="str"),
            "new_authenticator": Field(type="str"),
            "revoke": Field(type="bool"),
            "map_type": Field(
                type="str",
                choices=["allow", "is_superuser", "team", "organization", "role"],
            ),
            "team": Field(type="str"),
            "organization": Field(type="str"),
            "role": Field(type="str"),
            "triggers": Field(type="dict"),
            "order": Field(type="int"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_settings",
        roles=["gateway_settings"],
        component="gateway",
        is_list=False,
        item_schema={
            "settings": Field(type="dict"),
        },
    ),
    ResourceSchema(
        var="aap_organizations",
        roles=["gateway_organizations"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "custom_virtualenv": Field(type="str"),
            "max_hosts": Field(type="int"),
            "instance_groups": Field(type="list"),
            "default_environment": Field(type="str|dict"),
            "execution_environment": Field(type="str|dict", aliases=["default_environment"]),
            "galaxy_credentials": Field(type="list"),
            "notification_templates_approvals": Field(type="list"),
            "notification_templates_started": Field(type="list"),
            "notification_templates_success": Field(type="list"),
            "notification_templates_error": Field(type="list"),
            "state": Field(
                type="str",
                choices=["present", "absent", "exists", "enabled", "disabled"],
            ),
        },
    ),
    ResourceSchema(
        var="aap_applications",
        roles=["gateway_applications", "controller_applications"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "organization": Field(type="str", required=True, xref="aap_organizations.name"),
            "new_organization": Field(type="str"),
            "description": Field(type="str"),
            "authorization_grant_type": Field(type="str", choices=["password", "authorization-code"]),
            "client_type": Field(type="str", choices=["public", "confidential"]),
            "redirect_uris": Field(type="list"),
            "skip_authorization": Field(type="bool"),
            "algorithm": Field(type="str", choices=["", "RS256", "HS256"]),
            "post_logout_redirect_uris": Field(type="list"),
            "user": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_http_ports",
        roles=["gateway_http_ports"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "number": Field(type="int"),
            "use_https": Field(type="bool"),
            "is_api_port": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_service_clusters",
        roles=["gateway_service_clusters"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "service_type": Field(type="str"),
            "outlier_detection_enabled": Field(type="bool"),
            "outlier_detection_consecutive_5xx": Field(type="int"),
            "outlier_detection_interval_seconds": Field(type="int"),
            "outlier_detection_base_ejection_time_seconds": Field(type="int"),
            "outlier_detection_max_ejection_percent": Field(type="int"),
            "health_checks_enabled": Field(type="bool"),
            "health_check_timeout_seconds": Field(type="int"),
            "health_check_interval_seconds": Field(type="int"),
            "health_check_unhealthy_threshold": Field(type="int"),
            "health_check_healthy_threshold": Field(type="int"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_service_keys",
        roles=["gateway_service_keys"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "is_active": Field(type="bool"),
            "service_cluster": Field(type="str"),
            "algorithm": Field(type="str", choices=["HS256", "HS384", "HS512"]),
            "secret": Field(type="str"),
            "secret_length": Field(type="int"),
            "mark_previous_inactive": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_service_nodes",
        roles=["gateway_service_nodes"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "address": Field(type="str"),
            "service_cluster": Field(type="str"),
            "tags": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_services",
        roles=["gateway_services"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "api_slug": Field(type="str"),
            "http_port": Field(type="str"),
            "service_cluster": Field(type="str"),
            "is_service_https": Field(type="bool"),
            "enable_gateway_auth": Field(type="bool"),
            "service_path": Field(type="str"),
            "service_port": Field(type="int"),
            "node_tags": Field(type="str"),
            "order": Field(type="int"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="aap_teams",
        roles=["gateway_teams"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "organization": Field(type="str", xref="aap_organizations.name"),
            "new_organization": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="aap_user_accounts",
        roles=["gateway_users"],
        component="gateway",
        item_id_field="username",
        item_schema={
            "username": Field(type="str", required=True),
            "password": Field(type="str"),
            "email": Field(type="str"),
            "first_name": Field(type="str"),
            "last_name": Field(type="str"),
            "is_superuser": Field(type="bool", aliases=["superuser"]),
            "is_platform_auditor": Field(type="bool", aliases=["auditor"]),
            "update_secrets": Field(type="bool"),
            "organizations": Field(type="list"),
            "authenticators": Field(type="list"),
            "authenticator_uid": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_role_definitions",
        roles=["gateway_role_definitions"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "content_type": Field(type="str", required=True),
            "permissions": Field(type="list", required=True),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
    ResourceSchema(
        var="gateway_role_team_assignments",
        roles=["gateway_role_team_assignments"],
        component="gateway",
        item_id_field="role_definition",
        item_schema={
            "team": Field(type="str"),
            "team_ansible_id": Field(type="str"),
            "role_definition": Field(type="str"),
            "assignment_objects": Field(type="list"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="gateway_role_user_assignments",
        roles=["gateway_role_user_assignments"],
        component="gateway",
        item_id_field="role_definition",
        item_schema={
            "role_definition": Field(type="str", required=True),
            "user": Field(type="str"),
            "user_ansible_id": Field(type="str"),
            "object_id": Field(type="int"),
            "object_ids": Field(type="list"),
            "object_ansible_id": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="gateway_routes",
        roles=["gateway_routes"],
        component="gateway",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "gateway_path": Field(type="str"),
            "http_port": Field(type="str"),
            "service_cluster": Field(type="str"),
            "is_service_https": Field(type="bool"),
            "enable_gateway_auth": Field(type="bool"),
            "service_path": Field(type="str"),
            "service_port": Field(type="int"),
            "node_tags": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists", "enforced"]),
        },
    ),
]
