"""Schemas for Automation Hub resource types."""

from __future__ import annotations

from aap_config_validate.models import Field, ResourceSchema

HUB_SCHEMAS = [
    ResourceSchema(
        var="hub_namespaces",
        roles=["hub_namespace"],
        component="hub",
        item_schema={
            "name": Field(type="str", required=True),
            "new_name": Field(type="str"),
            "description": Field(type="str"),
            "company": Field(type="str"),
            "email": Field(type="str"),
            "avatar_url": Field(type="str"),
            "resources": Field(type="str"),
            "links": Field(type="list"),
            "groups": Field(type="list"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="hub_collections",
        roles=["hub_collection"],
        component="hub",
        item_schema={
            "namespace": Field(type="str", required=True),
            "name": Field(type="str", required=True),
            "version": Field(type="str"),
            "path": Field(type="str"),
            "repository": Field(type="str"),
            "wait": Field(type="bool"),
            "auto_approve": Field(type="bool"),
            "timeout": Field(type="int"),
            "interval": Field(type="int"),
            "overwrite_existing": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent"]),
        },
    ),
    ResourceSchema(
        var="hub_ee_registries",
        roles=["hub_ee_registry", "hub_ee_registry_index", "hub_ee_registry_sync"],
        component="hub",
        item_schema={
            "name": Field(type="str", required=True),
            "url": Field(type="str"),
            "username": Field(type="str"),
            "password": Field(type="str"),
            "tls_validation": Field(type="bool"),
            "is_indexable": Field(type="bool"),
            "policy": Field(type="str"),
            "download_concurrency": Field(type="int"),
            "rate_limit": Field(type="int"),
            "proxy_url": Field(type="str"),
            "proxy_username": Field(type="str"),
            "proxy_password": Field(type="str"),
            "index": Field(type="bool"),
            "sync": Field(type="bool"),
            "wait": Field(type="bool"),
            "interval": Field(type="int"),
            "timeout": Field(type="int"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="hub_ee_repositories",
        roles=["hub_ee_repository"],
        component="hub",
        item_schema={
            "name": Field(type="str", required=True),
            "description": Field(type="str"),
            "readme": Field(type="str"),
            "readme_file": Field(type="str"),
            "registry": Field(type="str"),
            "upstream_name": Field(type="str"),
            "include_tags": Field(type="list"),
            "exclude_tags": Field(type="list"),
            "sync": Field(type="bool"),
            "wait": Field(type="bool"),
            "interval": Field(type="int"),
            "timeout": Field(type="int"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="hub_ee_repository_sync",
        roles=["hub_ee_repository_sync"],
        component="hub",
        item_schema={
            "name": Field(type="str", required=True),
            "wait": Field(type="bool"),
            "interval": Field(type="int"),
            "timeout": Field(type="int"),
        },
    ),
    ResourceSchema(
        var="hub_ee_images",
        roles=["hub_ee_image"],
        component="hub",
        item_schema={
            "name": Field(type="str", required=True),
            "append": Field(type="bool"),
            "tags": Field(type="list"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="hub_collection_remotes",
        roles=["hub_collection_remote"],
        component="hub",
        item_schema={
            "name": Field(type="str", required=True),
            "url": Field(type="str"),
            "auth_url": Field(type="str"),
            "token": Field(type="str"),
            "policy": Field(type="str"),
            "requirements": Field(type="list"),
            "requirements_file": Field(type="str"),
            "username": Field(type="str"),
            "password": Field(type="str"),
            "tls_validation": Field(type="bool"),
            "client_key": Field(type="str"),
            "client_cert": Field(type="str"),
            "ca_cert": Field(type="str"),
            "client_key_path": Field(type="str"),
            "client_cert_path": Field(type="str"),
            "ca_cert_path": Field(type="str"),
            "download_concurrency": Field(type="int"),
            "max_retries": Field(type="int"),
            "rate_limit": Field(type="int"),
            "signed_only": Field(type="bool"),
            "sync_dependencies": Field(type="bool"),
            "proxy_url": Field(type="str"),
            "proxy_username": Field(type="str"),
            "proxy_password": Field(type="str"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
    ResourceSchema(
        var="hub_collection_repositories",
        roles=["hub_collection_repository", "hub_collection_repository_sync"],
        component="hub",
        item_schema={
            "name": Field(type="str", required=True),
            "description": Field(type="str"),
            "retain_repo_versions": Field(type="int"),
            "pulp_labels": Field(type="dict"),
            "distribution": Field(type="dict"),
            "private": Field(type="bool"),
            "remote": Field(type="str"),
            "update_repo": Field(type="bool"),
            "wait": Field(type="bool"),
            "interval": Field(type="int"),
            "timeout": Field(type="int"),
            "sync": Field(type="bool"),
            "state": Field(type="str", choices=["present", "absent", "exists"]),
        },
    ),
]
