---
bugfixes:
  - 'filetree_create - Export ``AWX_ANSIBLE_CALLBACK_PLUGINS`` and ``DEFAULT_EXECUTION_ENVIRONMENT`` in controller_settings via ``template_overrides_global.controller_setting`` defaults. Fixes #342.'
