---
# tasks file for object_diff
- name: "Resolve OAuth token for API queries"
  ansible.builtin.set_fact:
    __object_diff_oauth_token: >-
      {%- if ansible_facts.get('aap_token') is defined and ansible_facts.aap_token is mapping and (ansible_facts.aap_token.token is defined) -%} {{ ansible_facts.aap_token.token }}{%- elif ansible_facts.get('aap_token') is defined -%} {{ ansible_facts.aap_token }}{%- elif aap_token is defined and aap_token is mapping and (aap_token.token is defined) -%} {{ aap_token.token }}{%- elif aap_token is defined -%} {{ aap_token }}{%- else -%} {{ aap_oauthtoken }}{%- endif -%}
  tags:
    - always

- name: "Retrieve Ansible Tower or Automation Platform version"
  ansible.builtin.assert:
    that:
      - "aap_version is version('2.5', '>=')"
    fail_msg: "This role is only supported on AAP 2.5+. Use infra.controller_configuration.object_diff for earlier AAP/Ansible Tower versions."
  vars:
    aap_version: >-
      {{
        lookup(
          'ansible.platform.gateway_api',
          'api/gateway/v1/ping',
          host=aap_hostname,
          oauth_token=__object_diff_oauth_token,
          verify_ssl=aap_validate_certs
        ).version
      }}

- name: "Include Tasks to get OBJECT DIFF"
  ansible.builtin.include_tasks: "{{ __task_diff.name }}.yml"
  args:
    apply:
      tags: "{{ __task_diff.tags }}"
  tags:
    - always
  loop: "{{ controller_configuration_object_diff_tasks }}"
  loop_control:
    loop_var: __task_diff
...
