---
- name: "Get list of files inside {{ filetree_controller_credential_types }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_credential_types }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_controller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    recurse: true
  register: __list_files_controller_credential_types

- name: "Read Credential_Types definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_credentials_definitions_item.path }}"
  loop: "{{ __list_files_controller_credential_types.files }}"
  loop_control:
    loop_var: __read_credentials_definitions_item
  register: __contents_filetree_controller_credential_types
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_credential_types"

- name: "Populate Credential_Types list"
  ansible.builtin.set_fact:
    __populate_controller_credential_types: "{{ (__populate_controller_credential_types | default([])) + __populate_credentials_list_item.ansible_facts.controller_credential_types }}"
  loop: "{{ __contents_filetree_controller_credential_types.results }}"
  loop_control:
    loop_var: __populate_credentials_list_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_credential_types.results is defined and __populate_credentials_list_item.ansible_facts.controller_credential_types is defined

- name: "Set Projects Data Structure"
  ansible.builtin.set_fact:
    controller_credential_types: "{{ __populate_controller_credential_types }}"
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __populate_controller_credential_types is defined
...
