---
- name: "Get list of files inside {{ filetree_eda_projects }}"
  ansible.builtin.find:
    paths: "{{ filetree_eda_projects }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_controller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    contains: "eda_projects:"
    read_whole_file: true
    recurse: true
  register: __list_files_eda_projects

- name: "Read EDA projects definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_eda_projects_item.path }}"
  loop: "{{ __list_files_eda_projects.files }}"
  loop_control:
    loop_var: __read_eda_projects_item
  register: __contents_filetree_eda_projects
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_eda_projects"

- name: "Populate EDA projects list"
  ansible.builtin.set_fact:
    __populate_eda_projects: "{{ (__populate_eda_projects | default([])) + __populate_eda_projects_item.ansible_facts.eda_projects }}"
  loop: "{{ __contents_filetree_eda_projects.results }}"
  loop_control:
    loop_var: __populate_eda_projects_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when:
    - __contents_filetree_eda_projects is defined
    - __contents_filetree_eda_projects.results is defined
    - __contents_filetree_eda_projects.results | length > 0
    - __populate_eda_projects_item.ansible_facts.eda_projects is defined

- name: "Set EDA projects data structure"
  ansible.builtin.set_fact:
    eda_projects: "{{ __populate_eda_projects }}"
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __populate_eda_projects is defined
...
