---
- name: "Get list of files inside {{ filetree_gateway_authenticators }}"
  ansible.builtin.find:
    paths: "{{ filetree_gateway_authenticators }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_controller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    contains: "gateway_authenticators:"
    read_whole_file: true
    recurse: true
  register: __list_files_gateway_authenticators

- name: "Read Authenticators definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_authenticators_definitions_item.path }}"
  loop: "{{ __list_files_gateway_authenticators.files }}"
  loop_control:
    loop_var: __read_authenticators_definitions_item
  register: __contents_filetree_gateway_authenticators
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_gateway_authenticators"

- name: "Set Authenticators Data Structure"
  ansible.builtin.set_fact:
    gateway_authenticators: >-
      {{
        __contents_filetree_gateway_authenticators.results |
        rejectattr('ansible_facts.gateway_authenticators', 'undefined') |
        map(attribute='ansible_facts.gateway_authenticators') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when:
    - __contents_filetree_gateway_authenticators is defined
    - __contents_filetree_gateway_authenticators.results is defined
    - __contents_filetree_gateway_authenticators.results | length > 0
...
