---
- name: "Get list of files inside {{ filetree_gateway_authenticator_maps }}"
  ansible.builtin.find:
    paths: "{{ filetree_gateway_authenticator_maps }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_controller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    recurse: true
  register: __list_files_gateway_authenticator_maps

- name: "Read Authenticator Maps definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_authenticator_maps_definitions_item.path }}"
  loop: "{{ __list_files_gateway_authenticator_maps.files }}"
  loop_control:
    loop_var: __read_authenticator_maps_definitions_item
  register: __contents_filetree_gateway_authenticator_maps
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_gateway_authenticator_maps"

- name: "Set Authenticator Maps Data Structure"
  ansible.builtin.set_fact:
    gateway_authenticator_maps: >-
      {{
        __contents_filetree_gateway_authenticator_maps.results |
        rejectattr('ansible_facts.gateway_authenticator_maps', 'undefined') |
        map(attribute='ansible_facts.gateway_authenticator_maps') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when:
    - __contents_filetree_gateway_authenticator_maps is defined
    - __contents_filetree_gateway_authenticator_maps.results is defined
    - __contents_filetree_gateway_authenticator_maps.results | length > 0
...
