---
- name: "Get list of files inside {{ filetree_gateway_role_definitions }}"
  ansible.builtin.find:
    paths: "{{ filetree_gateway_role_definitions }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_controller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    contains: "gateway_role_definitions:"
    read_whole_file: true
    recurse: true
  register: __list_files_gateway_role_definitions

- name: "Read Role Definitions definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_role_definitions_definitions_item.path }}"
  loop: "{{ __list_files_gateway_role_definitions.files }}"
  loop_control:
    loop_var: __read_role_definitions_definitions_item
  register: __contents_filetree_gateway_role_definitions
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_gateway_role_definitions"

- name: "Set Role Definitions Data Structure"
  ansible.builtin.set_fact:
    gateway_role_definitions: >-
      {{
        __contents_filetree_gateway_role_definitions.results |
        rejectattr('ansible_facts.gateway_role_definitions', 'undefined') |
        map(attribute='ansible_facts.gateway_role_definitions') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when:
    - __contents_filetree_gateway_role_definitions is defined
    - __contents_filetree_gateway_role_definitions.results is defined
    - __contents_filetree_gateway_role_definitions.results | length > 0
...
