---
- name: "Get list of files inside {{ filetree_gateway_service_keys }}"
  ansible.builtin.find:
    paths: "{{ filetree_gateway_service_keys }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_controller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    recurse: true
  register: __list_files_gateway_service_keys

- name: "Read Service Keys definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_service_keys_definitions_item.path }}"
  loop: "{{ __list_files_gateway_service_keys.files }}"
  loop_control:
    loop_var: __read_service_keys_definitions_item
  register: __contents_filetree_gateway_service_keys
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_gateway_service_keys"

- name: "Set Service Keys Data Structure"
  ansible.builtin.set_fact:
    gateway_service_keys: >-
      {{
        __contents_filetree_gateway_service_keys.results |
        rejectattr('ansible_facts.gateway_service_keys', 'undefined') |
        map(attribute='ansible_facts.gateway_service_keys') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when:
    - __contents_filetree_gateway_service_keys is defined
    - __contents_filetree_gateway_service_keys.results is defined
    - __contents_filetree_gateway_service_keys.results | length > 0
...
