---
# tasks file for filetree_read
- name: "Include Tasks to config"
  ansible.builtin.include_tasks: "{{ __task_filetree_read.name }}.yml"
  args:
    apply:
      tags: "{{ __task_filetree_read.tags }}"
  when: >-
    ansible_run_tags | length == 0
    or 'all' in ansible_run_tags
    or (
      ansible_run_tags | intersect(
        [__task_filetree_read.tags] if __task_filetree_read.tags is string else __task_filetree_read.tags
      ) | length > 0
    )
  loop: "{{ controller_configuration_filetree_read_tasks }}"
  loop_control:
    loop_var: __task_filetree_read
    label: "{{ __task_filetree_read.name }}"
...
